Repository openid/AppAuth-iOS, pull requests merged in 2018-09, with the labels that each got.

#287 Fix typo (sha265 -> sha256)
  Source/OIDAuthorizationRequest.m
  Source/OIDTokenUtilities.h
  Source/OIDTokenUtilities.m
Labels: openid-cla: yes

#294 Run xcode 10 migration wizard
  AppAuth.xcodeproj/project.pbxproj
  AppAuth.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-iOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-macOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-tvOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth-watchOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth_iOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth_macOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth_tvOS.xcscheme
  AppAuth.xcodeproj/xcshareddata/xcschemes/AppAuth_watchOS.xcscheme
Labels: enhancement, openid-cla: yes

#296 Specify indent width in .xcodeproj
  AppAuth.xcodeproj/project.pbxproj
Labels: openid-cla: yes

#295 Ios12beta
  AppAuth.podspec
  AppAuth.xcodeproj/project.pbxproj
  Source/iOS/OIDExternalUserAgentIOS.m
Labels: openid-cla: yes

#298 Allow applications to use the "code id_token" response_type
  Source/OIDAuthState.h
  Source/OIDAuthState.m
  Source/OIDAuthorizationRequest.m
  Source/iOS/OIDAuthState+IOS.h
  Source/macOS/OIDAuthState+Mac.h
  UnitTests/OIDAuthorizationRequestTests.m
Labels: enhancement, in-scope, openid-cla: yes

#289 Add support for an initial access token to registration endpoint
  Source/OIDRegistrationRequest.h
  Source/OIDRegistrationRequest.m
  UnitTests/OIDRegistrationRequestTests.m
Labels: enhancement, in-scope, openid-cla: yes

#301 Remove `scope` from the token refresh request as it is redundant
  Source/OIDAuthState.m
Labels: openid-cla: yes
