Repository openid/AppAuth-iOS, pull requests merged in 2018-06, with the labels that each got.

#101 ID Token parsing and OpenID RP Certification
  AppAuth.xcodeproj/project.pbxproj
  Source/AppAuth.h
  Source/Framework/AppAuth.h
  Source/OIDAuthState.m
  Source/OIDAuthorizationRequest.h
  Source/OIDAuthorizationRequest.m
  Source/OIDAuthorizationService.h
  Source/OIDAuthorizationService.m
  Source/OIDError.h
  Source/OIDIDToken.h
  Source/OIDIDToken.m
  Source/OIDServiceConfiguration.h
  Source/OIDServiceConfiguration.m
  Source/OIDTokenResponse.h
  UnitTests/OIDAuthorizationRequestTests.m
  UnitTests/OIDRPProfileCode.h
  UnitTests/OIDRPProfileCode.m
Labels: enhancement, openid-cla: yes

#253 Create issue templates for bugs and feature requests.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, openid-cla: yes

#248 Add support for 4xx errors
  Source/OIDAuthorizationService.m
Labels: bug, openid-cla: yes

#257 Expose OIDURLSessionProvider to framework
  AppAuth.xcodeproj/project.pbxproj
  Source/Framework/AppAuth.h
Labels: bug, openid-cla: no

#250 Redact auth tokens in description methods
  AppAuth.xcodeproj/project.pbxproj
  Source/OIDAuthState.m
  Source/OIDAuthorizationResponse.m
  Source/OIDRegistrationResponse.m
  Source/OIDTokenResponse.m
  Source/OIDTokenUtilities.h
  Source/OIDTokenUtilities.m
  UnitTests/OIDTokenUtilitiesTests.m
Labels: enhancement, openid-cla: yes

#262 Add a description to errors, even if they have an underlyingError with a description
  Source/OIDAuthorizationService.m
  Source/OIDServiceDiscovery.m
  Source/iOS/OIDExternalUserAgentIOS.m
Labels: enhancement, openid-cla: yes
